---
title: '2019 Elemental Analyzer Reproducibility Report'
author: "Robin B. Trayler"
date: "`r format(Sys.time(), '%B, %d, %Y')`"
output:
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(magrittr)
library(lubridate)
```

```{r, echo = FALSE}
# define z-score function
zscore <- function(x){
  Z <- abs(mean(x, na.rm = T) - x) / sd(x, na.rm = T)
  return(Z)
}

```

# Report Setup
```{r echo = FALSE}
###         location of corrected data files to process
####################################################################
file_path = "~/Box Sync/Data Repository/EA/Corrected/2019"       ### 
####################################################################

# reference materials to check
standards = c('USGS 40', 
              'USGS 41a', 
              'costech acetanilide', 
              'MB squid', 
              'peach', 
              'EA sed',
              'bad acetanilide')

# outlier exclusion
exclude = 2 # exclude analyses that fall more that 2 standard deviations from the mean
# whole analyses are excluded if ANY of d13C, d15N, N%, C% are outliers
```


```{r echo = FALSE, warning=FALSE, message=FALSE, include=FALSE}
# get a list of all the csv files in the directory
files <- list.files(file_path, pattern = '.csv' , full.names = T)
# read in the first file to preallocate some storage
storage <- read_csv(file = files[2]) %>% 
  select(Identifier_1, 
         sample, 
         d13C_corrected, 
         d15N_corrected, 
         N_wt_percent, 
         C_wt_percent) %>% 
  mutate(date = ymd(str_sub(basename(files[1]), start = 3, end = 10))) %>% 
  mutate(sample = case_when(
    sample == 'costech acetanilide' & Identifier_1 == min(Identifier_1) ~ 'bad acetanilide',
    sample == 'costech acetanilide' & Identifier_1 == (min(Identifier_1) + 1) ~ 'bad acetanilide',
    TRUE ~ sample))




# loop through the remaining files and append them
for(i in 2:length(files)) {
  storage <- read_csv(file = files[i], col_names = T) %>% 
    select(Identifier_1, sample, 
           d13C_corrected, 
           d15N_corrected, 
           N_wt_percent, 
           C_wt_percent) %>% 
    mutate(date = ymd(str_sub(basename(files[i]), start = 3, end = 10))) %>% 
  mutate(sample = case_when(
    sample == 'costech acetanilide' & Identifier_1 == min(Identifier_1) ~ 'bad acetanilide',
    sample == 'costech acetanilide' & Identifier_1 == (min(Identifier_1) + 1) ~ 'bad acetanilide',
    TRUE ~ sample)) %>%
    full_join(storage)
}

```


```{r, echo = FALSE, include = FALSE}
# filter out the standards and remove outliers
storage = storage %>% filter(sample %in% standards) %>% 
  group_by(sample) %>% 
  mutate(d13C_zscore = zscore(d13C_corrected),
         d15N_zscore = zscore(d15N_corrected),
         N_zscore = zscore(N_wt_percent),
         C_zscore = zscore(C_wt_percent)) %>% 
  filter(d13C_zscore < exclude) %>% 
  filter( d15N_zscore < exclude) %>% 
  filter ( N_zscore < exclude) %>% 
  filter( C_zscore < exclude)
```

```{r include=FALSE}
# calculate summary statistics
storage_summary <- storage %>% 
  filter(sample %in% standards) %>% 
  group_by(sample) %>% 
  summarise(d13C_mean = mean(d13C_corrected, 
                             na.rm = T),
            d13C_sd = sd(d13C_corrected,
                         na.rm = T),
            d15N_mean = mean(d15N_corrected,
                             na.rm = T),
            d15N_sd = sd(d15N_corrected,
                         na.rm = T),
            C_wt_mean = mean(C_wt_percent,
                             na.rm = T),
            C_wt_sd = sd(C_wt_percent,
                         na.rm = T),
            N_wt_mean = mean(N_wt_percent,
                             na.rm = T),
            N_wt_sd = sd(N_wt_percent,
                         na.rm = T),
            n = length(d13C_corrected))

```

```{r echo=FALSE}
# make a table of the results
storage_summary %>%
  arrange(sample) %>% 
  knitr::kable(digits = 2, 
               col.names = c('Sample',
                             '$\\delta^{13}C_{mean}$', 
                             '$\\delta^{13}C_{sd}$', 
                             '$\\delta^{15}N_{mean}$',
                             '$\\delta^{15}N_{sd}$',
                             '$C \\%_{mean}$',
                             '$C \\%_{sd}$',
                             '$N \\%_{mean}$',
                             '$N \\%_{sd}$',
                             '$n$'),
               caption = 'Summary statistics and total number of analyses for commonly used reference materials.')
```


```{r, echo = FALSE, fig.align='center', fig.height= 9.5, fig.width=7.5}
par(oma = c(.1,.1,.1,.1))
layout(matrix(c(1,2,3,4), nrow = 2, byrow = T))
for(i in 1:length(standards)) {
  limit <- storage %>% filter(sample == standards[i]) %>% with(mean(d13C_corrected, na.rm = T))
  storage %>% filter(sample == standards[i]) %>% with(plot(x = date, 
                                                           y = d13C_corrected,
                                                           xlab = 'Date',
                                                           ylab = expression(delta^{13}~'C'),
                                                           ylim = as.vector(c(limit - 2, limit + 2)),
                                                           pch = 21,
                                                           bg = viridis::viridis(length(standards))[i],
                                                           main = standards[i],
                                                           tcl = 0.25))
  
  limit <- storage %>% filter(sample == standards[i]) %>% with(mean(d15N_corrected, na.rm = T))
  storage %>% filter(sample == standards[i]) %>% with(plot(x = date, 
                                                           y = d15N_corrected,
                                                           xlab = 'Date',
                                                           ylab = expression(delta^{15}~'N'),
                                                           ylim = as.vector(c(limit - 2, limit + 2)),
                                                           pch = 21,
                                                           bg = viridis::viridis(length(standards))[i],
                                                           main = standards[i],
                                                           tcl = 0.25))
  
  limit <- storage %>% filter(sample == standards[i]) %>% with(mean(C_wt_percent, na.rm = T))
  storage %>% filter(sample == standards[i]) %>% with(plot(x = date, 
                                                           y = C_wt_percent,
                                                           xlab = 'Date',
                                                           ylab = 'weight % carbon',
                                                           ylim = as.vector(c(limit - 3, limit + 3)),
                                                           pch = 21,
                                                           bg = viridis::viridis(length(standards))[i],
                                                           main = standards[i],
                                                           tcl = 0.25)) 
  
  limit <- storage %>% filter(sample == standards[i]) %>% with(mean(N_wt_percent, na.rm = T))
  storage %>% filter(sample == standards[i]) %>% with(plot(x = date, 
                                                           y = N_wt_percent,
                                                           xlab = 'Date',
                                                           ylab = 'weight % nitrogen',
                                                           ylim = as.vector(c(limit - 3, limit + 3)),
                                                           pch = 21,
                                                           bg = viridis::viridis(length(standards))[i],
                                                           main = standards[i],
                                                           tcl = 0.25)) 
}


```